# Generated by Django 4.2 on 2024-01-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='phone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='productfavorites',
            field=models.ManyToManyField(blank=True, null=True, to='products.product'),
        ),
    ]
