# Generated by Django 4.2 on 2024-01-25 18:32

from django.db import migrations, models
import settings.models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nav_ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('nav_ads_image', models.ImageField(upload_to=settings.models.image_upload, verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Nav_ads',
                'verbose_name_plural': 'Nav_ads',
            },
        ),
    ]
