# Generated by Django 4.2.3 on 2023-07-25 00:44

import creditcards.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Created At')),
                ('is_finished', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Cost')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'OrderDetails',
                'verbose_name_plural': 'OrderDetailss',
            },
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('cardholder', models.CharField(max_length=20, verbose_name='Card Holder')),
                ('cardnumber', creditcards.models.CardNumberField(max_length=16, verbose_name='Card Number')),
                ('expire', creditcards.models.CardExpiryField(verbose_name='Exepire Date')),
                ('security', creditcards.models.SecurityCodeField(max_length=4, verbose_name='CCV')),
                ('order_delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='Delivery Date')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
