# Generated by Django 4.2.3 on 2023-07-18 22:18

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BRDName', models.CharField(max_length=40, verbose_name='Name')),
                ('BRDDesc', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CATName', models.CharField(max_length=50, verbose_name='Name')),
                ('CATDes', models.TextField(verbose_name='Description')),
                ('CATImg', models.ImageField(upload_to='category', verbose_name='Images')),
                ('CATParent', models.ForeignKey(blank=True, limit_choices_to={'CATParent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Main Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRDname', models.CharField(max_length=300, verbose_name='product name')),
                ('PRDIImage', models.ImageField(blank=True, null=True, upload_to=products.models.image_upload, verbose_name='Image')),
                ('PRDDesc', models.TextField(verbose_name='Product Descripton')),
                ('PRDquantity', models.DecimalField(decimal_places=0, default='0', max_digits=10, verbose_name='َQuantity')),
                ('purchasingprice', models.DecimalField(decimal_places=0, default='0', max_digits=10, verbose_name='Purchasing Price')),
                ('PRDPrice', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Price')),
                ('PRDPriceDiscount', models.DecimalField(decimal_places=0, default='0', max_digits=5, verbose_name='discount')),
                ('PRDCost', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Cost')),
                ('PRDCreated', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('PRDIs_Active', models.BooleanField(default=False, verbose_name='Active')),
                ('PRDNew', models.BooleanField(default=True, verbose_name='New-Product')),
                ('PRDSeller', models.BooleanField(default=False, verbose_name='Bestseller')),
                ('PRDBrand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.brand', verbose_name='Brand')),
                ('PRDcategory', models.ForeignKey(blank=True, limit_choices_to={'CATParent__isnull': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Categery')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-PRDNew'],
            },
        ),
    ]
